title: Nagharjun Mathi Mariappan # your name (or website title) here
logo: "/images/IMG_8743 2.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Research Assistant working on Large Language Models. Previously worked as a Data Scientist at LOCOMeX Inc. Graduate Student at NYU.
  <br><br>
  I love leveraging machine learning to build software applications. My work helps me find the best ways to solve real-world problems.
  <br><br>
  <a href="https://www.linkedin.com/in/nagharjun-mathi-mariappan-b61499169/"><i class="fab fa-linkedin"></i> View My LinkedIn Profile</a>
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
